# Generated by Django 3.0.8 on 2020-07-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='price',
        ),
    ]
